version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     ports:
       - "33306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress1234
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress1234

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./docker_wordpress:/var/www/html
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress1234
volumes:
    db_data:
