version: '3.3'

services:
   db:
     image: mysql:5.7
     ports:
       - "33306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress1234
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress1234

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress1234
       WORDPRESS_DB_NAME: wordpress

   wordpress_exporter:
     depends_on:
       - db
     image: erwin82/wordpress_exporter:latest
     ports:
       - "8888:8888"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress1234
       WORDPRESS_DB_NAME: wordpress
